language: haskell
env:
    - CUDA=6.5-14 GHC=7.6.3
    - CUDA=6.5-14 GHC=7.8.4
    - CUDA=6.5-14 GHC=7.10.1
    - CUDA=7.0-28 GHC=7.6.3
    - CUDA=7.0-28 GHC=7.8.4
    - CUDA=7.0-28 GHC=7.10.1
    - CUDA=7.0-28 GHC=head
#    - CUDA=6.0-37

matrix:
    allow_failures:
        - env: CUDA=7.0-28 GHC=head

before_install:
    # If travis doesn't have the version of GHC that we want, get it from hvr's PPA
    - echo "Setting up GHC"
    - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
    - travis_retry sudo apt-get update -qq
    - travis_retry sudo apt-get install -y c2hs
    - export PATH=/usr/local/ghc/${GHC}/bin:${PATH}
    - |
        if [ $(ghc --numeric-version) != ${GHC} ]; then
            travis_retry sudo apt-get install -y ghc-${GHC}
            export PATH=/opt/ghc/${GHC}/bin:${PATH}
        fi

    # If we want to build c2hs from source, ghc-7.8 and later will require newer
    # versions of happy and alex
    #    - |
    #        if [ ${GHC%.*} != 7.6 ]; then
    #            travis_retry sudo apt-get install -y happy-1.19.4 alex-3.1.3
    #            export PATH=/opt/alex/3.1.3/bin:/opt/happy/1.19.4/bin:${PATH}
    #        fi
    #    - cabal install c2hs

    - echo "Installing CUDA library"
    - travis_retry wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1204/x86_64/cuda-repo-ubuntu1204_${CUDA}_amd64.deb
    - travis_retry sudo dpkg -i cuda-repo-ubuntu1204_${CUDA}_amd64.deb
    - travis_retry sudo apt-get update -qq
    - export CUDA_APT=${CUDA%-*}
    - export CUDA_APT=${CUDA_APT/./-}
#    - travis_retry sudo apt-get install -y cuda-${CUDA_APT}
    - travis_retry sudo apt-get install -y cuda-drivers cuda-core-${CUDA_APT} cuda-cudart-dev-${CUDA_APT} cuda-cufft-dev-${CUDA_APT}
    - travis_retry sudo apt-get clean
    - export CUDA_HOME=/usr/local/cuda-${CUDA%%-*}
    - export LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}
    - export PATH=${CUDA_HOME}/bin:${PATH}

install:
    - ghc --version
    - cabal --version
    - nvcc --version
    - cabal install --only-dependencies --enable-tests

script:
    # Check the build
    - cabal configure -v2 -flib-Werror
    - cabal build
    - cabal haddock
#    - cabal test --show-details=always

    # Check the source distribution can be generated, built, and installed
    - cabal sdist
    - |
        export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}')
        cd dist
        if [ -f "$SRC_TGZ" ]; then
            cabal install --force-reinstalls ${SRC_TGZ} || exit 1
        else
            echo "'$SRC_TGZ': not found"
            exit 1
        fi

after_failure:
    - dmesg
    - ls -R /usr/local/cuda*

